# Generated by Django 3.1 on 2020-11-28 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminer', '0002_auto_20201124_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='is_business',
            field=models.BooleanField(default=False),
        ),
    ]
