# Generated by Django 3.1 on 2020-10-12 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='thumbnail_image',
            field=models.URLField(blank=True, default='https://monorbit-alpha.s3-us-west-2.amazonaws.com/Content/images/undraw_team_up_ip2x.svg', null=True),
        ),
        migrations.AlterField(
            model_name='networkcategory',
            name='image',
            field=models.URLField(blank=True, default='https://monorbit-alpha.s3-us-west-2.amazonaws.com/Content/images/undraw_team_up_ip2x.svg', null=True),
        ),
        migrations.AlterField(
            model_name='networkdocument',
            name='doc',
            field=models.URLField(blank=True, default='https://monorbit-alpha.s3-us-west-2.amazonaws.com/Content/images/undraw_team_up_ip2x.svg', null=True),
        ),
        migrations.AlterField(
            model_name='networkimage',
            name='image',
            field=models.URLField(blank=True, default='https://monorbit-alpha.s3-us-west-2.amazonaws.com/Content/images/undraw_team_up_ip2x.svg', null=True),
        ),
        migrations.AlterField(
            model_name='networktype',
            name='image',
            field=models.URLField(blank=True, default='https://monorbit-alpha.s3-us-west-2.amazonaws.com/Content/images/undraw_team_up_ip2x.svg', null=True),
        ),
        migrations.AlterField(
            model_name='networkvideo',
            name='video',
            field=models.URLField(blank=True, default='https://monorbit-alpha.s3-us-west-2.amazonaws.com/Content/images/undraw_team_up_ip2x.svg', null=True),
        ),
    ]
