# Generated by Django 3.1 on 2020-08-31 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_network_is_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkoperationtiming',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
