# Generated by Django 3.1 on 2020-09-09 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_networkoperationtiming_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='followers',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='networkoperationtiming',
            name='day',
            field=models.CharField(blank=True, choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday'), ('All', 'All'), ('Weekday', 'Weekday'), ('Weekend', 'Weekend')], default='All', max_length=255, null=True),
        ),
    ]
