# Generated by Django 3.1 on 2020-11-30 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_auto_20201116_2324'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkStat',
            fields=[
                ('id', models.CharField(blank=True, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('total_income', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('orders_recieved', models.IntegerField(blank=True, default=0, null=True)),
                ('total_sales', models.IntegerField(blank=True, default=0, help_text='Total number of meaningful orders', null=True)),
                ('refunds', models.IntegerField(blank=True, default=0, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.network')),
            ],
        ),
    ]
