# Generated by Django 3.1 on 2020-12-20 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_networkstat'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='comment',
            field=models.TextField(blank=True, help_text='This field will tell about the personal comment about the network. Only for admin purpose.', null=True),
        ),
        migrations.CreateModel(
            name='NetworkOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_special_user', models.BooleanField(default=False, help_text='This field will tell whether the network is a special network on monorbit')),
                ('is_backer', models.BooleanField(default=False, help_text='This field will tell whether the network is the backer or sponsor of Monorbit Platform')),
                ('is_kyc', models.BooleanField(default=False, help_text='This field will tell whether the KYC of the network have been done or not')),
                ('is_address_private', models.BooleanField(default=False, help_text='This field when true will keep the address of the network private.')),
                ('is_phone_and_email_private', models.BooleanField(default=False, help_text='This field when true will keep the phone number and email of the network private')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.network')),
            ],
        ),
    ]
