# Generated by Django 3.1 on 2020-09-27 15:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_auto_20200909_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkJob',
            fields=[
                ('id', models.CharField(blank=True, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('job_name', models.CharField(blank=True, max_length=255, null=True)),
                ('job_type', models.CharField(blank=True, choices=[('freelancer', 'Freelancer'), ('delivery', 'Delivery'), ('permanent', 'Permanent')], default='permanent', max_length=255, null=True)),
                ('job_description', models.TextField(blank=True, null=True)),
                ('job_requirements', models.TextField(blank=True, null=True)),
                ('salary_payout_type', models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('bimonthly', 'Bi Monthly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('biyearly', 'Bi Yearly'), ('yearly', 'Yearly'), ('work', 'Work Basis')], default='monthly', max_length=255, null=True)),
                ('salary_lower_range', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('salary_upper_range', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('actual_salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('age_bar_upper', models.IntegerField(blank=True, default=45, null=True)),
                ('age_bar_lower', models.IntegerField(blank=True, default=18, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_spam', models.BooleanField(default=False)),
                ('is_vacant', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.network')),
            ],
        ),
        migrations.CreateModel(
            name='NetworkJobOffering',
            fields=[
                ('id', models.CharField(blank=True, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('offering_information', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_filled', models.BooleanField(default=False)),
                ('max_staff_for_job', models.IntegerField(blank=True, default=5, null=True)),
                ('last_date', models.DateField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.networkjob')),
            ],
        ),
    ]
