# Generated by Django 3.1 on 2020-12-22 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_auto_20201220_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkoption',
            name='network',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='network.network'),
        ),
    ]
