# Generated by Django 3.1 on 2020-09-30 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_profiles', '0002_auto_20200827_1750'),
        ('network', '0005_networkjob_networkjoboffering'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkStaff',
            fields=[
                ('id', models.CharField(blank=True, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('application_id', models.CharField(blank=True, max_length=20, null=True)),
                ('promoted_count', models.IntegerField(default=0)),
                ('demoted_count', models.IntegerField(default=0)),
                ('employee_score', models.IntegerField(default=10, help_text='This score would be given to employee out of 10.')),
                ('is_active', models.BooleanField(default=True)),
                ('joined', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.networkjob')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_profiles.jobprofile')),
            ],
        ),
    ]
