# Generated by Django 3.1 on 2021-01-21 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_auto_20201222_1921'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkTrial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicable_offer', models.CharField(blank=True, choices=[('republic', 'Republic'), ('normal', 'Normal')], default='normal', max_length=255, null=True)),
                ('trial_days', models.IntegerField(blank=True, default=30, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('network', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='network.network')),
            ],
        ),
    ]
