# Generated by Django 3.1 on 2020-10-01 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_networkstaff'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='network_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
