# Generated by Django 3.1 on 2020-10-07 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_profiles', '0002_auto_20200827_1750'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermanentEmployeeSkill',
            fields=[
                ('id', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('expert', 'Expert')], default='beginner', max_length=50)),
                ('label', models.CharField(blank=True, help_text='Label of the Specification', max_length=255, null=True)),
                ('description', models.TextField(blank=True, help_text='Description of the Specification', null=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('permanent_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_profiles.permanentemployee')),
            ],
            options={
                'verbose_name': 'Permanent Employee Skill',
                'verbose_name_plural': 'Permanent Employee Skills',
            },
        ),
        migrations.CreateModel(
            name='PermanentEmployeeExperience',
            fields=[
                ('id', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(blank=True, help_text='Title of the Specification', max_length=255, null=True)),
                ('organization', models.CharField(blank=True, help_text=' of the Specification', max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateField(default='10-08-2020')),
                ('end_date', models.DateField(default='10-08-2020')),
                ('description', models.TextField(blank=True, help_text='Description of the Specification', null=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('permanent_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_profiles.permanentemployee')),
            ],
            options={
                'verbose_name': 'Permanent Employee Experience',
                'verbose_name_plural': 'Permanent Employee Experience',
            },
        ),
        migrations.CreateModel(
            name='PermanentEmployeeEducation',
            fields=[
                ('id', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(blank=True, help_text='Title of the Specification', max_length=255, null=True)),
                ('specialization', models.CharField(blank=True, help_text='Title of the Specification', max_length=255, null=True)),
                ('organization', models.CharField(blank=True, help_text=' of the Specification', max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateField(default='10-08-2020')),
                ('end_date', models.DateField(default='10-08-2020')),
                ('description', models.TextField(blank=True, help_text='Description of the Specification', null=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('permanent_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_profiles.permanentemployee')),
            ],
            options={
                'verbose_name': 'Permanent Employee Education',
                'verbose_name_plural': 'Permanent Employee Education',
            },
        ),
        migrations.CreateModel(
            name='FreelancerSkill',
            fields=[
                ('id', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('expert', 'Expert')], default='beginner', max_length=50)),
                ('label', models.CharField(blank=True, help_text='Label of the Specification', max_length=255, null=True)),
                ('description', models.TextField(blank=True, help_text='Description of the Specification', null=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_profiles.freelancer')),
            ],
            options={
                'verbose_name': 'Freelancer Skill',
                'verbose_name_plural': 'Freelancer Skills',
            },
        ),
        migrations.CreateModel(
            name='FreelancerExperience',
            fields=[
                ('id', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(blank=True, help_text='Title of the Specification', max_length=255, null=True)),
                ('organization', models.CharField(blank=True, help_text=' of the Specification', max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateField(default='10-08-2020')),
                ('end_date', models.DateField(default='10-08-2020')),
                ('description', models.TextField(blank=True, help_text='Description of the Specification', null=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_profiles.freelancer')),
            ],
            options={
                'verbose_name': 'Freelancer Experience',
                'verbose_name_plural': 'Freelancer Experience',
            },
        ),
        migrations.CreateModel(
            name='FreelancerEducation',
            fields=[
                ('id', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(blank=True, help_text='Title of the Specification', max_length=255, null=True)),
                ('specialization', models.CharField(blank=True, help_text='Title of the Specification', max_length=255, null=True)),
                ('organization', models.CharField(blank=True, help_text=' of the Specification', max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateField(default='10-08-2020')),
                ('end_date', models.DateField(default='10-08-2020')),
                ('description', models.TextField(blank=True, help_text='Description of the Specification', null=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_profiles.freelancer')),
            ],
            options={
                'verbose_name': 'Freelancer Education',
                'verbose_name_plural': 'Freelancer Education',
            },
        ),
    ]
