# Generated by Django 3.1 on 2020-10-12 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(blank=True, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('item_code', models.CharField(blank=True, max_length=112, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('brand_name', models.CharField(blank=True, max_length=255, null=True)),
                ('barcode', models.CharField(blank=True, max_length=255, null=True)),
                ('thumbnail_image', models.URLField(blank=True, default='https://content.monorbit.com/images/placeholder.png', null=True)),
                ('mrp', models.DecimalField(decimal_places=2, default=0.0, help_text='This would be Maximum Retail Price', max_digits=12)),
                ('nsp', models.DecimalField(decimal_places=2, default=0.0, help_text='Net Selling Price - The price at which they offer', max_digits=12)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0.0, help_text='dp = nsp/mrp * 100', max_digits=12)),
                ('tax', models.DecimalField(decimal_places=2, default=0.0, help_text='Tax on the Product', max_digits=12)),
                ('shipping', models.DecimalField(decimal_places=2, default=0.0, help_text='Shipping charge for the product', max_digits=12)),
                ('quantity_per_measurement', models.IntegerField(blank=True, default=1, null=True)),
                ('short_description', models.TextField(blank=True, null=True)),
                ('rating', models.DecimalField(decimal_places=1, default=5.0, max_digits=2)),
                ('no_of_reviews', models.IntegerField(blank=True, default=0, null=True)),
                ('available_in_stock', models.IntegerField(blank=True, default=1, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('is_open_for_sharing', models.BooleanField(default=False)),
                ('is_digital', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCustomCategory',
            fields=[
                ('id', models.CharField(blank=True, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.URLField(blank=True, default='https://content.monorbit.com/images/placeholder.png', null=True)),
                ('network', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='network.network')),
            ],
        ),
        migrations.CreateModel(
            name='ProductDefaultCategory',
            fields=[
                ('id', models.CharField(blank=True, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.URLField(blank=True, default='https://content.monorbit.com/images/placeholder.png', null=True)),
                ('network_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.networkcategory')),
            ],
        ),
        migrations.CreateModel(
            name='ProductMeasurement',
            fields=[
                ('id', models.CharField(blank=True, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('full_form', models.CharField(blank=True, max_length=112, null=True)),
                ('short_form', models.CharField(blank=True, max_length=25, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductVideo',
            fields=[
                ('id', models.CharField(blank=True, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('video', models.URLField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_catalog.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('id', models.CharField(blank=True, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_catalog.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSpecification',
            fields=[
                ('id', models.CharField(blank=True, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('key', models.CharField(blank=True, max_length=100, null=True)),
                ('value', models.TextField(blank=True, null=True)),
                ('measured_in', models.CharField(blank=True, max_length=50, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_catalog.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.CharField(blank=True, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('size', models.CharField(blank=True, max_length=255, null=True)),
                ('change_side', models.BooleanField(default=True, help_text='If True, then the change would be positive, otherwise - negative')),
                ('price_change', models.DecimalField(decimal_places=2, default=0.0, help_text='This will be the Price Change from the Original Product Price', max_digits=12)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_catalog.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.CharField(blank=True, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('rating', models.DecimalField(decimal_places=1, default=5.0, max_digits=2)),
                ('comment', models.TextField(blank=True, null=True)),
                ('is_spam', models.BooleanField(default=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_catalog.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.CharField(blank=True, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.URLField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_catalog.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductExtra',
            fields=[
                ('id', models.CharField(blank=True, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('key', models.CharField(blank=True, max_length=100, null=True)),
                ('value', models.TextField(blank=True, null=True)),
                ('change_side', models.BooleanField(default=True, help_text='If True, then the change would be positive, otherwise - negative')),
                ('price_change', models.DecimalField(decimal_places=2, default=0.0, help_text='This will be the Price Change from the Original Product Price', max_digits=12)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_catalog.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductDocument',
            fields=[
                ('id', models.CharField(blank=True, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('doc', models.URLField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_catalog.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductDefaultSubCategory',
            fields=[
                ('id', models.CharField(blank=True, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.URLField(blank=True, default='https://content.monorbit.com/images/placeholder.png', null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_catalog.productdefaultcategory')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCustomSubCategory',
            fields=[
                ('id', models.CharField(blank=True, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.URLField(blank=True, default='https://content.monorbit.com/images/placeholder.png', null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_catalog.productcustomcategory')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='custom_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_catalog.productcustomcategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='custom_subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_catalog.productcustomsubcategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='default_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_catalog.productdefaultcategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='default_subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_catalog.productdefaultsubcategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='measurement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_catalog.productmeasurement'),
        ),
        migrations.AddField(
            model_name='product',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.network'),
        ),
    ]
