# Generated by Django 3.1 on 2020-08-11 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
        ('product_catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdefaultcategory',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.network'),
        ),
        migrations.AlterField(
            model_name='productdefaultcategory',
            name='network_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.networkcategory'),
        ),
    ]
