# Generated by Django 3.1 on 2020-08-12 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_catalog', '0002_auto_20200812_0209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdefaultcategory',
            name='network',
        ),
    ]
