# Generated by Django 3.1 on 2020-12-02 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_catalog', '0003_productcolor'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='minimum_quantity_per_order',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
