# Generated by Django 3.1 on 2020-08-14 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_catalog', '0004_auto_20200813_0101'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shipping',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Shipping charge for the product', max_digits=12),
        ),
    ]
