# Generated by Django 3.1 on 2020-12-04 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_catalog', '0004_product_minimum_quantity_per_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_refundable',
            field=models.BooleanField(default=False, help_text='Is the current product is refundable?'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_returnable',
            field=models.BooleanField(default=False, help_text='Is the current product is returnable?'),
        ),
    ]
