# Generated by Django 3.1 on 2020-12-09 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_catalog', '0005_auto_20201204_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_refundable',
            field=models.BooleanField(blank=True, default=False, help_text='Is the current product is refundable?', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_returnable',
            field=models.BooleanField(blank=True, default=False, help_text='Is the current product is returnable?', null=True),
        ),
    ]
