# Generated by Django 3.1 on 2020-08-31 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_network_is_premium'),
        ('product_catalog', '0005_product_shipping'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcustomcategory',
            name='network',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='network.network'),
        ),
    ]
