# Generated by Django 3.1 on 2021-01-26 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_networktrial_expiry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product_catalog', '0006_auto_20201209_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='available_in_stock',
            field=models.IntegerField(blank=True, default=1, help_text='No of quantity of product which is available in stock', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, help_text='Products bar code', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand_name',
            field=models.CharField(blank=True, help_text='Products brand name - Eg. Gucci', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp at which the product have been added'),
        ),
        migrations.AlterField(
            model_name='product',
            name='custom_category',
            field=models.ForeignKey(blank=True, help_text='Reference to the Custom Product Category for which the product have been added. Can be relplaceable with Default Product Category. Should only be one of these present, not both of them for any product', null=True, on_delete=django.db.models.deletion.CASCADE, to='product_catalog.productcustomcategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='custom_subcategory',
            field=models.ForeignKey(blank=True, help_text='Reference to the Custom Product Sub Category for which the product have been added. Should only be paired with Custom Product Category', null=True, on_delete=django.db.models.deletion.CASCADE, to='product_catalog.productcustomsubcategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='default_category',
            field=models.ForeignKey(blank=True, help_text='Reference to the Default Product Category for which the product have been added. Can be replaceable with Custom Product Category', null=True, on_delete=django.db.models.deletion.CASCADE, to='product_catalog.productdefaultcategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='default_subcategory',
            field=models.ForeignKey(blank=True, help_text='Reference to the Default Sub Category for which the product have been added. Should only be paired with Default Product Category', null=True, on_delete=django.db.models.deletion.CASCADE, to='product_catalog.productdefaultsubcategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.CharField(blank=True, help_text='Primary Key of the Product', max_length=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is the current product is active or being deactivated?'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Is the current product have been moved to the archived vault?'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_digital',
            field=models.BooleanField(default=False, help_text='Is the product is going to be sold digitally and has no physical significance. like a software or a movie being transfered through FTP.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_open_for_sharing',
            field=models.BooleanField(default=False, help_text='Is the network is ready to share the product data with the other sellers'),
        ),
        migrations.AlterField(
            model_name='product',
            name='item_code',
            field=models.CharField(blank=True, help_text='Unique Item Code for the Product. This will be used for advanced purposes in the future.', max_length=112, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='measurement',
            field=models.ForeignKey(blank=True, help_text='Reference to the Measurement in which the product is going to be measured', null=True, on_delete=django.db.models.deletion.CASCADE, to='product_catalog.productmeasurement'),
        ),
        migrations.AlterField(
            model_name='product',
            name='minimum_quantity_per_order',
            field=models.IntegerField(blank=True, default=1, help_text='Minimum no of quantity that need to be placed for the order of this particular product', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, help_text='Product Name', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='network',
            field=models.ForeignKey(help_text='Reference to the Network who have added the Product', on_delete=django.db.models.deletion.CASCADE, to='network.network'),
        ),
        migrations.AlterField(
            model_name='product',
            name='no_of_reviews',
            field=models.IntegerField(blank=True, default=0, help_text='No of total reviews that have given on the product by users', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity_per_measurement',
            field=models.IntegerField(blank=True, default=1, help_text='This would be quantity for measurement unit - e.g. 100gm, 100 is quantity and gm is unit', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=5.0, help_text='Rating for the product that users have given', max_digits=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=models.TextField(blank=True, help_text='Short Description about the product', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.CharField(blank=True, help_text="Product Slug automatcially generated from the product's name", max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail_image',
            field=models.URLField(blank=True, default='https://monorbit-alpha.s3-us-west-2.amazonaws.com/Content/images/undraw_team_up_ip2x.svg', help_text='Products thumbnail image - This will be short image that can be used for specific purposes', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp at which the product have been updated'),
        ),
        migrations.AlterField(
            model_name='productcolor',
            name='color',
            field=models.CharField(blank=True, help_text='Title of the color e.g. Royal Black', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='productcolor',
            name='id',
            field=models.CharField(blank=True, help_text='Primary key of the Product Color', max_length=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='productcolor',
            name='product',
            field=models.ForeignKey(help_text='Reference to the Product to which this color belongs to', on_delete=django.db.models.deletion.CASCADE, to='product_catalog.product'),
        ),
        migrations.AlterField(
            model_name='productcustomcategory',
            name='id',
            field=models.CharField(blank=True, help_text='Primary Key of the Product Custom Category', max_length=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='productcustomcategory',
            name='image',
            field=models.URLField(blank=True, default='https://monorbit-alpha.s3-us-west-2.amazonaws.com/Content/images/undraw_team_up_ip2x.svg', help_text='Display image of the Product Custom Category', null=True),
        ),
        migrations.AlterField(
            model_name='productcustomcategory',
            name='name',
            field=models.CharField(blank=True, help_text='Name of the Product Custom Category', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='productcustomcategory',
            name='network',
            field=models.ForeignKey(blank=True, help_text='Reference to the Network who is creating the particular custom product category or belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, to='network.network'),
        ),
        migrations.AlterField(
            model_name='productcustomsubcategory',
            name='category',
            field=models.ForeignKey(help_text='Reference to the Product Custom Category to which this subcategory belongs to or being created for', on_delete=django.db.models.deletion.CASCADE, to='product_catalog.productcustomcategory'),
        ),
        migrations.AlterField(
            model_name='productcustomsubcategory',
            name='id',
            field=models.CharField(blank=True, help_text='Primary key of the Product Custom Sub Category', max_length=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='productcustomsubcategory',
            name='image',
            field=models.URLField(blank=True, default='https://monorbit-alpha.s3-us-west-2.amazonaws.com/Content/images/undraw_team_up_ip2x.svg', help_text='Display image of the Product Custom Sub Category', null=True),
        ),
        migrations.AlterField(
            model_name='productcustomsubcategory',
            name='name',
            field=models.CharField(blank=True, help_text='Name of the Product Custom Subcategory', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='productdefaultcategory',
            name='id',
            field=models.CharField(blank=True, help_text='Primary Key of the default Product Category', max_length=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='productdefaultcategory',
            name='image',
            field=models.URLField(blank=True, default='https://monorbit-alpha.s3-us-west-2.amazonaws.com/Content/images/undraw_team_up_ip2x.svg', help_text='Display image of the Product Default Category', null=True),
        ),
        migrations.AlterField(
            model_name='productdefaultcategory',
            name='name',
            field=models.CharField(blank=True, help_text='Name of the Product Default Category', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='productdefaultcategory',
            name='network_category',
            field=models.ForeignKey(help_text='Reference to the Network category for which this product default category is going to be created or belongs to', on_delete=django.db.models.deletion.CASCADE, to='network.networkcategory'),
        ),
        migrations.AlterField(
            model_name='productdefaultsubcategory',
            name='category',
            field=models.ForeignKey(help_text='Reference to the Product Default Category under which this product default sub category is going to be created or belongs to', on_delete=django.db.models.deletion.CASCADE, to='product_catalog.productdefaultcategory'),
        ),
        migrations.AlterField(
            model_name='productdefaultsubcategory',
            name='id',
            field=models.CharField(blank=True, help_text='Primary Key of the default Product Sub Category', max_length=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='productdefaultsubcategory',
            name='image',
            field=models.URLField(blank=True, default='https://monorbit-alpha.s3-us-west-2.amazonaws.com/Content/images/undraw_team_up_ip2x.svg', help_text='Display image of the Product Default Sub Category', null=True),
        ),
        migrations.AlterField(
            model_name='productdefaultsubcategory',
            name='name',
            field=models.CharField(blank=True, help_text='Name of the Product Default Sub Category', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='productdocument',
            name='doc',
            field=models.URLField(blank=True, default='https://monorbit-alpha.s3-us-west-2.amazonaws.com/Content/images/undraw_team_up_ip2x.svg', help_text='Actual URL of the document', null=True),
        ),
        migrations.AlterField(
            model_name='productdocument',
            name='id',
            field=models.CharField(blank=True, help_text='Primary Key of the Product Document', max_length=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='productdocument',
            name='label',
            field=models.CharField(blank=True, help_text='Lable of the document. It means what the document depicts actually', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='productdocument',
            name='product',
            field=models.ForeignKey(help_text='Reference to the product for which this document belongs to', on_delete=django.db.models.deletion.CASCADE, to='product_catalog.product'),
        ),
        migrations.AlterField(
            model_name='productextra',
            name='id',
            field=models.CharField(blank=True, help_text='Primary Key of the Product Extra', max_length=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='productextra',
            name='key',
            field=models.CharField(blank=True, help_text='Key of the Extra add on e.g. Earphone', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productextra',
            name='product',
            field=models.ForeignKey(help_text='Reference to the Product to which this extra add on belongs to', on_delete=django.db.models.deletion.CASCADE, to='product_catalog.product'),
        ),
        migrations.AlterField(
            model_name='productextra',
            name='value',
            field=models.TextField(blank=True, help_text='Value of the Extra add on e.g. Wireless bluetooth earphone with 30h battery life is the Value here', null=True),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='id',
            field=models.CharField(blank=True, help_text='Primary Key of the Product Image', max_length=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.URLField(blank=True, default='https://monorbit-alpha.s3-us-west-2.amazonaws.com/Content/images/undraw_team_up_ip2x.svg', help_text='Actual URL of the image. This URL will be filled automatically after uploading the image to the Storage Bucket', null=True),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='label',
            field=models.CharField(blank=True, help_text='Label of the image. It means what the image depits actually', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(help_text='Reference to the product for which this image belongs to', on_delete=django.db.models.deletion.CASCADE, to='product_catalog.product'),
        ),
        migrations.AlterField(
            model_name='productmeasurement',
            name='active',
            field=models.BooleanField(default=True, help_text='This field will determine whether the Measurement unit is deprecated or not.'),
        ),
        migrations.AlterField(
            model_name='productmeasurement',
            name='full_form',
            field=models.CharField(blank=True, help_text='Full form of the Product Measurement Unit, e.g - Kilo Gram', max_length=112, null=True),
        ),
        migrations.AlterField(
            model_name='productmeasurement',
            name='id',
            field=models.CharField(blank=True, help_text='Primary key of the Product Measurement', max_length=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='productmeasurement',
            name='short_form',
            field=models.CharField(blank=True, help_text='Short form of the Product Measurement Unit, e.g - KG', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='by',
            field=models.ForeignKey(help_text='Reference to the user who have given the review', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='comment',
            field=models.TextField(blank=True, help_text='Tells about the comment user leaved about the product in the review', null=True),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp at which the user have given the review on the product'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='id',
            field=models.CharField(blank=True, help_text='Primary Key of the Product Review', max_length=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='is_active',
            field=models.BooleanField(default=True, help_text='If true, the review is active. If false, review is no more valid.'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='is_spam',
            field=models.BooleanField(default=False, help_text='If true, the review will be marked as spam and will not be considered for product rating calculation'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='product',
            field=models.ForeignKey(help_text='Reference to the Product for which the review have given', on_delete=django.db.models.deletion.CASCADE, to='product_catalog.product'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=5.0, help_text='This will tell how much the user rated the product - It varies between 1 and 5', max_digits=2),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='id',
            field=models.CharField(blank=True, help_text='Primary Key of the Product Size', max_length=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='product',
            field=models.ForeignKey(help_text='Reference to the Product to which this size belongs to', on_delete=django.db.models.deletion.CASCADE, to='product_catalog.product'),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='size',
            field=models.CharField(blank=True, help_text='Size title e.g. 4GB+32GB', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='id',
            field=models.CharField(blank=True, help_text='Primary Key of the Product Specification', max_length=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='key',
            field=models.CharField(blank=True, help_text='Key of the Specification e.g. RAM here is the Key', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='measured_in',
            field=models.CharField(blank=True, help_text='Measuring unit of the Specification e.g. GB is the measurement unit here', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='product',
            field=models.ForeignKey(help_text='Reference to the Product to which this specification belongs to', on_delete=django.db.models.deletion.CASCADE, to='product_catalog.product'),
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='value',
            field=models.TextField(blank=True, help_text='Value of the Specification e.g. 4 is the Value here', null=True),
        ),
        migrations.AlterField(
            model_name='producttag',
            name='id',
            field=models.CharField(blank=True, help_text='Primary Key of the Product Tag', max_length=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='producttag',
            name='name',
            field=models.CharField(blank=True, help_text='Name of the tag e.g Best Earphone below 200', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='producttag',
            name='product',
            field=models.ForeignKey(help_text='Reference to the Product for which this tag belongs to', on_delete=django.db.models.deletion.CASCADE, to='product_catalog.product'),
        ),
        migrations.AlterField(
            model_name='productvideo',
            name='id',
            field=models.CharField(blank=True, help_text='Primary key of the Product Video', max_length=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='productvideo',
            name='label',
            field=models.CharField(blank=True, help_text='Label of the video. It means wht the image depicts actually', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='productvideo',
            name='product',
            field=models.ForeignKey(help_text='Reference to the product for which this video belongs to', on_delete=django.db.models.deletion.CASCADE, to='product_catalog.product'),
        ),
        migrations.AlterField(
            model_name='productvideo',
            name='video',
            field=models.URLField(blank=True, default='https://monorbit-alpha.s3-us-west-2.amazonaws.com/Content/images/undraw_team_up_ip2x.svg', help_text='Actual URL of the video. This URL will be filled automatically after uploading the video to the Storage Bucket', null=True),
        ),
    ]
