# Generated by Django 3.1 on 2021-02-17 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_catalog', '0008_product_is_stock_unlimited'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTopping',
            fields=[
                ('id', models.CharField(blank=True, help_text='Primary key of the Product topping', max_length=10, primary_key=True, serialize=False, unique=True)),
                ('topping', models.CharField(blank=True, help_text='Topping name', max_length=255, null=True)),
                ('description', models.TextField(blank=True, help_text="Description of the product's topping.", null=True)),
                ('price_change', models.DecimalField(decimal_places=2, help_text='Price of toppins', max_digits=3)),
                ('up_down_side', models.BooleanField(default=False)),
            ],
        ),
    ]
