# Generated by Django 3.1 on 2021-02-19 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_catalog', '0010_producttopping_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttopping',
            name='price_change',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Price of toppins', max_digits=12),
        ),
    ]
