# Generated by Django 3.1 on 2020-08-11 20:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyotp',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 12, 2, 4, 10, 992332), null=True),
        ),
        migrations.AlterField(
            model_name='emailverifyotp',
            name='expiry',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 12, 2, 34, 10, 992199), null=True),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 12, 2, 4, 10, 989946), null=True),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expiry',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 12, 3, 4, 10, 989814), null=True),
        ),
    ]
