# Generated by Django 3.1 on 2020-11-22 04:12

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import monorbit.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyotp',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='This is the timestamp at which OTP is created'),
        ),
        migrations.AlterField(
            model_name='emailverifyotp',
            name='otp',
            field=models.CharField(blank=True, help_text='This is the OTP Sent to the user', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='emailverifyotp',
            name='user',
            field=models.ForeignKey(help_text='This is the user reference who is requesting the OTP', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='This is the timestamp at which OTP is created'),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='token',
            field=models.CharField(blank=True, help_text='This is the OTP Sent to the user', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='user',
            field=models.ForeignKey(help_text='This is the user reference who is requesting the OTP', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, help_text="User's city of current residence", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='country_code',
            field=models.IntegerField(blank=True, default=91, help_text='This will be the country code of the user from which he/she is accessing the monorbit', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.CharField(blank=True, default='22-01-2000', help_text='This would be the Date of birth of the user in the format - DD-MM-YYYY', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, help_text="This will be the user's primary email", max_length=255, null=True, validators=[django.core.validators.EmailValidator, monorbit.utils.validators.custom_email_validator]),
        ),
        migrations.AlterField(
            model_name='user',
            name='followed_networks',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='It is the total number of networks a user joined to', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, help_text="This will be the user's full name", max_length=255, null=True, verbose_name='full_name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Transgender', 'Transgender'), ('Custom', 'Custom')], default='Male', help_text='This will be the gender of the user - Choices are predefined above and should be changed only in accounts/models.py', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='hash_token',
            field=models.CharField(blank=True, help_text='This is long unique token that will be used for advanced purposes like app level authentication, etc.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(blank=True, help_text='Primary Key of the user model', max_length=20, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='This will determine whether the user account is active or not'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False, help_text='This will determine is the user is a super user or not'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='This will determine whether the user have deleted his/her account or not.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_creator',
            field=models.BooleanField(default=False, help_text='This will determine whether the user is a creator or business. Default it will be false'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_logged_in',
            field=models.BooleanField(default=False, help_text='This will determine whether the user is logged in or not.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_logged_in_time',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='This will determine when the user logged in last time'),
        ),
        migrations.AlterField(
            model_name='user',
            name='network_created',
            field=models.IntegerField(blank=True, default=0, help_text='It is the number of total network created by the user', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='order_count',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='It the total number of orders placed by the user on Monorbit Ecommerce', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_sent',
            field=models.IntegerField(blank=True, default=0, help_text='It the total number of OTP Sent to user in order to verify his/her phone number.', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password_otp_sent',
            field=models.IntegerField(blank=True, default=0, help_text='It is the total number of password reset OTP sent to the user in case the user forgot his/her password', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='pincode',
            field=models.CharField(blank=True, help_text="User's Locality postal code of current residence", max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='registration_reference',
            field=models.CharField(blank=True, default='None', help_text='This would be the registration reference from which user have joined Monorbit', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, help_text='This will determine when the user updated his/her account details'),
        ),
        migrations.AlterField(
            model_name='userlocalization',
            name='communication_language_code',
            field=models.CharField(blank=True, choices=[('af', 'afrikaans'), ('sq', 'albanian'), ('am', 'amharic'), ('ar', 'arabic'), ('hy', 'armenian'), ('az', 'azerbaijani'), ('eu', 'basque'), ('be', 'belarusian'), ('bn', 'bengali'), ('bs', 'bosnian'), ('bg', 'bulgarian'), ('ca', 'catalan'), ('ceb', 'cebuano'), ('ny', 'chichewa'), ('zh-cn', 'chinese (simplified)'), ('zh-tw', 'chinese (traditional)'), ('co', 'corsican'), ('hr', 'croatian'), ('cs', 'czech'), ('da', 'danish'), ('nl', 'dutch'), ('en', 'english'), ('eo', 'esperanto'), ('et', 'estonian'), ('tl', 'filipino'), ('fi', 'finnish'), ('fr', 'french'), ('fy', 'frisian'), ('gl', 'galician'), ('ka', 'georgian'), ('de', 'german'), ('el', 'greek'), ('gu', 'gujarati'), ('ht', 'haitian creole'), ('ha', 'hausa'), ('haw', 'hawaiian'), ('iw', 'hebrew'), ('he', 'hebrew'), ('hi', 'hindi'), ('hmn', 'hmong'), ('hu', 'hungarian'), ('is', 'icelandic'), ('ig', 'igbo'), ('id', 'indonesian'), ('ga', 'irish'), ('it', 'italian'), ('ja', 'japanese'), ('jw', 'javanese'), ('kn', 'kannada'), ('kk', 'kazakh'), ('km', 'khmer'), ('ko', 'korean'), ('ku', 'kurdish (kurmanji)'), ('ky', 'kyrgyz'), ('lo', 'lao'), ('la', 'latin'), ('lv', 'latvian'), ('lt', 'lithuanian'), ('lb', 'luxembourgish'), ('mk', 'macedonian'), ('mg', 'malagasy'), ('ms', 'malay'), ('ml', 'malayalam'), ('mt', 'maltese'), ('mi', 'maori'), ('mr', 'marathi'), ('mn', 'mongolian'), ('my', 'myanmar (burmese)'), ('ne', 'nepali'), ('no', 'norwegian'), ('or', 'odia'), ('ps', 'pashto'), ('fa', 'persian'), ('pl', 'polish'), ('pt', 'portuguese'), ('pa', 'punjabi'), ('ro', 'romanian'), ('ru', 'russian'), ('sm', 'samoan'), ('gd', 'scots gaelic'), ('sr', 'serbian'), ('st', 'sesotho'), ('sn', 'shona'), ('sd', 'sindhi'), ('si', 'sinhala'), ('sk', 'slovak'), ('sl', 'slovenian'), ('so', 'somali'), ('es', 'spanish'), ('su', 'sundanese'), ('sw', 'swahili'), ('sv', 'swedish'), ('tg', 'tajik'), ('ta', 'tamil'), ('te', 'telugu'), ('th', 'thai'), ('tr', 'turkish'), ('uk', 'ukrainian'), ('ur', 'urdu'), ('ug', 'uyghur'), ('uz', 'uzbek'), ('vi', 'vietnamese'), ('cy', 'welsh'), ('xh', 'xhosa'), ('yi', 'yiddish'), ('yo', 'yoruba'), ('zu', 'zulu')], default='en', help_text='This is the language used by user for communication purposes like chat, calls, support, etc.', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='userlocalization',
            name='interface_language_code',
            field=models.CharField(blank=True, choices=[('af', 'afrikaans'), ('sq', 'albanian'), ('am', 'amharic'), ('ar', 'arabic'), ('hy', 'armenian'), ('az', 'azerbaijani'), ('eu', 'basque'), ('be', 'belarusian'), ('bn', 'bengali'), ('bs', 'bosnian'), ('bg', 'bulgarian'), ('ca', 'catalan'), ('ceb', 'cebuano'), ('ny', 'chichewa'), ('zh-cn', 'chinese (simplified)'), ('zh-tw', 'chinese (traditional)'), ('co', 'corsican'), ('hr', 'croatian'), ('cs', 'czech'), ('da', 'danish'), ('nl', 'dutch'), ('en', 'english'), ('eo', 'esperanto'), ('et', 'estonian'), ('tl', 'filipino'), ('fi', 'finnish'), ('fr', 'french'), ('fy', 'frisian'), ('gl', 'galician'), ('ka', 'georgian'), ('de', 'german'), ('el', 'greek'), ('gu', 'gujarati'), ('ht', 'haitian creole'), ('ha', 'hausa'), ('haw', 'hawaiian'), ('iw', 'hebrew'), ('he', 'hebrew'), ('hi', 'hindi'), ('hmn', 'hmong'), ('hu', 'hungarian'), ('is', 'icelandic'), ('ig', 'igbo'), ('id', 'indonesian'), ('ga', 'irish'), ('it', 'italian'), ('ja', 'japanese'), ('jw', 'javanese'), ('kn', 'kannada'), ('kk', 'kazakh'), ('km', 'khmer'), ('ko', 'korean'), ('ku', 'kurdish (kurmanji)'), ('ky', 'kyrgyz'), ('lo', 'lao'), ('la', 'latin'), ('lv', 'latvian'), ('lt', 'lithuanian'), ('lb', 'luxembourgish'), ('mk', 'macedonian'), ('mg', 'malagasy'), ('ms', 'malay'), ('ml', 'malayalam'), ('mt', 'maltese'), ('mi', 'maori'), ('mr', 'marathi'), ('mn', 'mongolian'), ('my', 'myanmar (burmese)'), ('ne', 'nepali'), ('no', 'norwegian'), ('or', 'odia'), ('ps', 'pashto'), ('fa', 'persian'), ('pl', 'polish'), ('pt', 'portuguese'), ('pa', 'punjabi'), ('ro', 'romanian'), ('ru', 'russian'), ('sm', 'samoan'), ('gd', 'scots gaelic'), ('sr', 'serbian'), ('st', 'sesotho'), ('sn', 'shona'), ('sd', 'sindhi'), ('si', 'sinhala'), ('sk', 'slovak'), ('sl', 'slovenian'), ('so', 'somali'), ('es', 'spanish'), ('su', 'sundanese'), ('sw', 'swahili'), ('sv', 'swedish'), ('tg', 'tajik'), ('ta', 'tamil'), ('te', 'telugu'), ('th', 'thai'), ('tr', 'turkish'), ('uk', 'ukrainian'), ('ur', 'urdu'), ('ug', 'uyghur'), ('uz', 'uzbek'), ('vi', 'vietnamese'), ('cy', 'welsh'), ('xh', 'xhosa'), ('yi', 'yiddish'), ('yo', 'yoruba'), ('zu', 'zulu')], default='en', help_text='This is the language that user can set in order how he want to view the application', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='userlocalization',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp at which localization is created'),
        ),
        migrations.AlterField(
            model_name='userlocalization',
            name='updated',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp at which localization is updated'),
        ),
        migrations.AlterField(
            model_name='userlocalization',
            name='user',
            field=models.ForeignKey(help_text="This is the user's reference to which localization is setting up", on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
