# Generated by Django 3.1 on 2020-08-05 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200805_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='network_created',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
