# Generated by Django 3.1 on 2020-08-11 20:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200812_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyotp',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 12, 2, 9, 46, 213213), null=True),
        ),
        migrations.AlterField(
            model_name='emailverifyotp',
            name='expiry',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 12, 2, 39, 46, 213093), null=True),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 12, 2, 9, 46, 210926), null=True),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expiry',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 12, 3, 9, 46, 210799), null=True),
        ),
    ]
