# Generated by Django 3.1 on 2020-08-12 10:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200812_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyotp',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 12, 16, 5, 44, 391334), null=True),
        ),
        migrations.AlterField(
            model_name='emailverifyotp',
            name='expiry',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 12, 16, 35, 44, 391205), null=True),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 12, 16, 5, 44, 378982), null=True),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expiry',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 12, 17, 5, 44, 378847), null=True),
        ),
    ]
