# Generated by Django 3.1 on 2020-08-12 19:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200812_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyotp',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 13, 1, 1, 30, 81542), null=True),
        ),
        migrations.AlterField(
            model_name='emailverifyotp',
            name='expiry',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 13, 1, 31, 30, 81429), null=True),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 13, 1, 1, 30, 79401), null=True),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expiry',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 13, 2, 1, 30, 79213), null=True),
        ),
    ]
