# Generated by Django 3.1 on 2020-08-14 08:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200814_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='order_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='emailverifyotp',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 14, 13, 59, 58, 547752), null=True),
        ),
        migrations.AlterField(
            model_name='emailverifyotp',
            name='expiry',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 14, 14, 29, 58, 547563), null=True),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 14, 13, 59, 58, 545292), null=True),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expiry',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 14, 14, 59, 58, 545123), null=True),
        ),
    ]
