# Generated by Django 3.1 on 2020-08-18 09:35

import accounts.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200816_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyotp',
            name='created',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='emailverifyotp',
            name='expiry',
            field=models.DateTimeField(blank=True, default=accounts.models.expiration_delta, null=True),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='created',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expiry',
            field=models.DateTimeField(blank=True, default=accounts.models.expiration_delta, null=True),
        ),
    ]
