# Generated by Django 3.1 on 2020-09-09 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20200831_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='followed_networks',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
