# Generated by Django 3.1 on 2020-12-13 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('network', '0004_networkstat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(blank=True, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('item_code', models.CharField(blank=True, max_length=112, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('brand_name', models.CharField(blank=True, max_length=255, null=True)),
                ('barcode', models.CharField(blank=True, max_length=255, null=True)),
                ('thumbnail_image', models.URLField(blank=True, default='https://monorbit-alpha.s3-us-west-2.amazonaws.com/Content/images/undraw_team_up_ip2x.svg', null=True)),
                ('mrp', models.DecimalField(decimal_places=2, default=0.0, help_text='This would be Maximum Retail Price', max_digits=12)),
                ('nsp', models.DecimalField(decimal_places=2, default=0.0, help_text='Net Selling Price - The price at which they offer', max_digits=12)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0.0, help_text='dp = nsp/mrp * 100', max_digits=12)),
                ('quantity_per_measurement', models.IntegerField(blank=True, default=1, null=True)),
                ('short_description', models.TextField(blank=True, null=True)),
                ('minimum_quantity_per_order', models.IntegerField(blank=True, default=1, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_digital', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.CharField(blank=True, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.URLField(blank=True, default='https://monorbit-alpha.s3-us-west-2.amazonaws.com/Content/images/undraw_team_up_ip2x.svg', null=True)),
                ('network_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.networkcategory')),
            ],
        ),
        migrations.CreateModel(
            name='ProductMeasurement',
            fields=[
                ('id', models.CharField(blank=True, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('full_form', models.CharField(blank=True, max_length=112, null=True)),
                ('short_form', models.CharField(blank=True, max_length=25, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductVideo',
            fields=[
                ('id', models.CharField(blank=True, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('video', models.URLField(blank=True, default='https://monorbit-alpha.s3-us-west-2.amazonaws.com/Content/images/undraw_team_up_ip2x.svg', null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo_product.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('id', models.CharField(blank=True, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo_product.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSubCategory',
            fields=[
                ('id', models.CharField(blank=True, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.URLField(blank=True, default='https://monorbit-alpha.s3-us-west-2.amazonaws.com/Content/images/undraw_team_up_ip2x.svg', null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo_product.productcategory')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSpecification',
            fields=[
                ('id', models.CharField(blank=True, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('key', models.CharField(blank=True, max_length=100, null=True)),
                ('value', models.TextField(blank=True, null=True)),
                ('measured_in', models.CharField(blank=True, max_length=50, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo_product.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.CharField(blank=True, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('size', models.CharField(blank=True, max_length=255, null=True)),
                ('change_side', models.BooleanField(default=True, help_text='If True, then the change would be positive, otherwise - negative')),
                ('price_change', models.DecimalField(decimal_places=2, default=0.0, help_text='This will be the Price Change from the Original Product Price', max_digits=12)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo_product.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.CharField(blank=True, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.URLField(blank=True, default='https://monorbit-alpha.s3-us-west-2.amazonaws.com/Content/images/undraw_team_up_ip2x.svg', null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo_product.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductExtra',
            fields=[
                ('id', models.CharField(blank=True, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('key', models.CharField(blank=True, max_length=100, null=True)),
                ('value', models.TextField(blank=True, null=True)),
                ('change_side', models.BooleanField(default=True, help_text='If True, then the change would be positive, otherwise - negative')),
                ('price_change', models.DecimalField(decimal_places=2, default=0.0, help_text='This will be the Price Change from the Original Product Price', max_digits=12)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo_product.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductDocument',
            fields=[
                ('id', models.CharField(blank=True, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('doc', models.URLField(blank=True, default='https://monorbit-alpha.s3-us-west-2.amazonaws.com/Content/images/undraw_team_up_ip2x.svg', null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo_product.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.CharField(blank=True, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('color', models.CharField(blank=True, max_length=255, null=True)),
                ('change_side', models.BooleanField(default=True, help_text='If True, then the change would be positive, otherwise - negative')),
                ('price_change', models.DecimalField(decimal_places=2, default=0.0, help_text='This will be the Price Change from the Original Product Price', max_digits=12)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo_product.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='demo_product.productcategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='measurement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='demo_product.productmeasurement'),
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='demo_product.productsubcategory'),
        ),
    ]
