# Generated by Django 3.1 on 2021-03-09 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FCMDevice',
            fields=[
                ('id', models.CharField(blank=True, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('resitration_id', models.CharField(blank=True, max_length=255, null=True)),
                ('device_type', models.CharField(blank=True, choices=[('android', 'android'), ('ios', 'iso'), ('web', 'wed')], default='web', max_length=122, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.CharField(blank=True, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('message_title', models.CharField(blank=True, max_length=512, null=True)),
                ('message_body', models.TextField(blank=True, null=True)),
                ('fcmdevice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fcm_message.fcmdevice')),
            ],
        ),
    ]
