# Generated by Django 3.1 on 2021-03-10 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fcm_message', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fcmdevice',
            old_name='resitration_id',
            new_name='registration_id',
        ),
    ]
