# Generated by Django 3.1 on 2020-10-12 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('network', '0001_initial'),
        ('job_profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkPermanentEmployeeApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_status', models.CharField(blank=True, choices=[('applied', 'Applied'), ('in_touch', 'In Touch'), ('hired', 'Hired'), ('fired', 'Fired'), ('rejected', 'Rejected')], default='applied', max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.networkjoboffering')),
                ('permanent_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_profiles.permanentemployee')),
            ],
        ),
        migrations.CreateModel(
            name='NetworkFreelancerApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_status', models.CharField(blank=True, choices=[('applied', 'Applied'), ('in_touch', 'In Touch'), ('hired', 'Hired'), ('fired', 'Fired'), ('rejected', 'Rejected')], default='applied', max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_profiles.freelancer')),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.networkjoboffering')),
            ],
        ),
        migrations.CreateModel(
            name='NetworkFollower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.network')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NetworkDeliveryBoyApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_status', models.CharField(blank=True, choices=[('applied', 'Applied'), ('in_touch', 'In Touch'), ('hired', 'Hired'), ('fired', 'Fired'), ('rejected', 'Rejected')], default='applied', max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('delivery_boy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_profiles.deliveryboy')),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.networkjoboffering')),
            ],
        ),
    ]
