# Generated by Django 3.1 on 2020-09-30 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_profiles', '0002_auto_20200827_1750'),
        ('network', '0006_networkstaff'),
        ('transactions', '0002_auto_20200924_1931'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkPermanentEmployeeApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_status', models.CharField(blank=True, choices=[('applied', 'Applied'), ('in_touch', 'In Touch'), ('hired', 'Hired'), ('fired', 'Fired'), ('rejected', 'Rejected')], default='applied', max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.networkjoboffering')),
                ('permanent_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_profiles.permanentemployee')),
            ],
        ),
        migrations.CreateModel(
            name='NetworkFreelancerApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_status', models.CharField(blank=True, choices=[('applied', 'Applied'), ('in_touch', 'In Touch'), ('hired', 'Hired'), ('fired', 'Fired'), ('rejected', 'Rejected')], default='applied', max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_profiles.freelancer')),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.networkjoboffering')),
            ],
        ),
        migrations.CreateModel(
            name='NetworkDeliveryBoyApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_status', models.CharField(blank=True, choices=[('applied', 'Applied'), ('in_touch', 'In Touch'), ('hired', 'Hired'), ('fired', 'Fired'), ('rejected', 'Rejected')], default='applied', max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('delivery_boy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_profiles.deliveryboy')),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.networkjoboffering')),
            ],
        ),
    ]
