# Generated by Django 3.1 on 2020-10-18 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('greivances', '0002_faqcategory_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='greivances.faqcategory'),
        ),
    ]
