# Generated by Django 3.1 on 2020-11-16 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_catalog', '0003_productcolor'),
        ('cart', '0002_auto_20201026_0216'),
    ]

    operations = [
        migrations.AddField(
            model_name='productentry',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_catalog.productcolor'),
        ),
        migrations.AddField(
            model_name='productentry',
            name='extra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_catalog.productextra'),
        ),
        migrations.AddField(
            model_name='productentry',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_catalog.productsize'),
        ),
    ]
