# Generated by Django 3.1 on 2020-11-22 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20201116_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='productentry',
            name='product_status',
            field=models.CharField(blank=True, choices=[('not_valid', 'Not Valid'), ('in_cart', 'In Cart'), ('order_created', 'Order Created'), ('order_confirmed', 'Order Confirmed'), ('order_shipped', 'Order shipped'), ('order_dispatched', 'Order dispatched'), ('order_out_for_delivery', 'Order out for delivery'), ('order_delivered', 'Order Delivered'), ('order_cancelled', 'Order Cancelled'), ('order_returned', 'Order Returned'), ('order_refunded', 'Order Refunded')], default='in_cart', help_text='This will determine order status for an individual product', max_length=255, null=True),
        ),
    ]
