# Generated by Django 3.1 on 2021-03-08 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_productentry_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='productentry',
            name='is_pickup',
            field=models.BooleanField(default=False),
        ),
    ]
