# Generated by Django 3.1 on 2021-03-13 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_productentry_is_pickup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productentry',
            name='is_pickup',
        ),
    ]
