# Generated by Django 3.1 on 2020-08-27 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('network', '0002_network_is_premium'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkMembershipPlan',
            fields=[
                ('id', models.CharField(blank=True, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, choices=[('Basic', 'Basic'), ('Economy', 'Economy'), ('Elite', 'Elite')], default='Basic', max_length=125, null=True)),
                ('price_per_day', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NetworkMembershipRelation',
            fields=[
                ('id', models.CharField(blank=True, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('network', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='network.network')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='premium.networkmembershipplan')),
            ],
        ),
        migrations.CreateModel(
            name='NetworkMembershipPlanFeatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='premium.networkmembershipplan')),
            ],
        ),
        migrations.CreateModel(
            name='NetworkMembershipActivity',
            fields=[
                ('id', models.CharField(blank=True, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('payment', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('active_till', models.IntegerField(blank=True, default=365, null=True)),
                ('active', models.BooleanField(default=True)),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='premium.networkmembershiprelation')),
            ],
        ),
    ]
