# Generated by Django 3.1 on 2020-10-12 12:09

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkBilling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('landmark', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('network', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='network.network')),
            ],
        ),
        migrations.CreateModel(
            name='NetworkMembershipActivity',
            fields=[
                ('id', models.CharField(blank=True, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateField(default=django.utils.timezone.now)),
                ('trial_expiry', models.DateField(default=datetime.datetime(2021, 10, 12, 12, 9, 46, 266024, tzinfo=utc))),
                ('trial_active_till', models.IntegerField(blank=True, default=365, null=True)),
                ('trial_applied', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='NetworkMembershipOrderReciept',
            fields=[
                ('id', models.CharField(blank=True, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('order_id', models.CharField(blank=True, max_length=50, null=True)),
                ('entity', models.CharField(blank=True, max_length=50, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('amount_due', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('transaction_charge', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('currency', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('attempts', models.IntegerField(blank=True, default=0, null=True)),
                ('created_at_rzp', models.BigIntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('network', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='network.network')),
            ],
        ),
        migrations.CreateModel(
            name='NetworkMembershipPlan',
            fields=[
                ('id', models.CharField(blank=True, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, choices=[('Basic', 'Basic'), ('Economy', 'Economy'), ('Elite', 'Elite')], default='Basic', max_length=125, null=True)),
                ('price_per_day', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NetworkMembershipSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('started', models.DateField(default=django.utils.timezone.now)),
                ('is_trial', models.BooleanField(default=False)),
                ('expiry', models.DateField(default=datetime.datetime(2021, 10, 12, 12, 9, 46, 266024, tzinfo=utc))),
                ('active_till', models.IntegerField(blank=True, default=365, null=True)),
                ('active', models.BooleanField(default=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='premium.networkmembershipactivity')),
                ('billing_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='premium.networkbilling')),
                ('network_order_receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='premium.networkmembershiporderreciept')),
            ],
        ),
        migrations.CreateModel(
            name='NetworkMembershipRelation',
            fields=[
                ('id', models.CharField(blank=True, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('network', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='network.network')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='premium.networkmembershipplan')),
            ],
        ),
        migrations.CreateModel(
            name='NetworkMembershipPlanFeatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='premium.networkmembershipplan')),
            ],
        ),
        migrations.CreateModel(
            name='NetworkMembershipPaymentInvoice',
            fields=[
                ('id', models.CharField(blank=True, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('account_id', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_id', models.CharField(blank=True, max_length=50, null=True)),
                ('order_id', models.CharField(blank=True, max_length=50, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('network_order_receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='premium.networkmembershiporderreciept')),
            ],
        ),
        migrations.CreateModel(
            name='NetworkMembershipInvoice',
            fields=[
                ('id', models.CharField(blank=True, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('invoice_period_start_date', models.DateField(blank=True, null=True)),
                ('invoice_period_end_date', models.DateField(blank=True, null=True)),
                ('invoice_description', models.TextField(blank=True, null=True)),
                ('invoice_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('invoice_created', models.DateTimeField(auto_now_add=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='premium.networkmembershipsubscription')),
            ],
        ),
        migrations.AddField(
            model_name='networkmembershipactivity',
            name='relation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='premium.networkmembershiprelation'),
        ),
    ]
