# Generated by Django 3.1 on 2020-08-27 10:16

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('premium', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkmembershipactivity',
            name='expiry',
            field=models.DateField(default=datetime.datetime(2021, 8, 27, 10, 16, 9, 897417, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='networkmembershipactivity',
            name='created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
