# Generated by Django 3.1 on 2020-08-27 10:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('premium', '0002_auto_20200827_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkmembershipactivity',
            name='expiry',
            field=models.DateField(default=datetime.datetime(2021, 8, 27, 10, 19, 41, 210568, tzinfo=utc)),
        ),
    ]
