# Generated by Django 3.1 on 2020-08-27 10:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('premium', '0004_auto_20200827_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkmembershipactivity',
            name='expiry',
            field=models.DateField(default=datetime.datetime(2021, 8, 27, 10, 21, 59, 920896, tzinfo=utc)),
        ),
    ]
