# Generated by Django 3.1 on 2020-10-28 08:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('premium', '0005_auto_20201026_0216'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkmembershipactivity',
            name='activity_downgrade_limit',
            field=models.DateField(default=datetime.datetime(2021, 1, 26, 8, 40, 13, 340957, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='networkmembershipactivity',
            name='activity_upgrade_limit',
            field=models.DateField(default=datetime.datetime(2021, 1, 26, 8, 40, 13, 340957, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='networkmembershipactivity',
            name='trial_expiry',
            field=models.DateField(default=datetime.datetime(2021, 10, 28, 8, 40, 13, 340957, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='networkmembershipsubscription',
            name='expiry',
            field=models.DateField(default=datetime.datetime(2021, 10, 28, 8, 40, 13, 340957, tzinfo=utc)),
        ),
    ]
