# Generated by Django 3.1 on 2020-08-27 10:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('premium', '0006_auto_20200827_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkmembershipactivity',
            name='expiry',
            field=models.DateField(default=datetime.datetime(2021, 8, 27, 10, 23, 11, 670692, tzinfo=utc)),
        ),
    ]
