# Generated by Django 3.1 on 2020-08-31 07:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('premium', '0007_auto_20200827_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkmembershipactivity',
            name='expiry',
            field=models.DateField(default=datetime.datetime(2021, 8, 31, 7, 19, 36, 546703, tzinfo=utc)),
        ),
    ]
