# Generated by Django 3.1 on 2020-08-31 07:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('premium', '0008_auto_20200831_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkmembershipactivity',
            name='expiry',
            field=models.DateField(default=datetime.datetime(2021, 8, 31, 7, 20, 4, 708029, tzinfo=utc)),
        ),
    ]
