# Generated by Django 3.1 on 2020-08-31 11:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('premium', '0011_auto_20200831_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkmembershipactivity',
            name='expiry',
            field=models.DateField(default=datetime.datetime(2021, 8, 31, 11, 19, 46, 326605, tzinfo=utc)),
        ),
    ]
