# Generated by Django 3.1 on 2020-09-01 11:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('premium', '0012_auto_20200831_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkmembershipactivity',
            name='expiry',
            field=models.DateField(default=datetime.datetime(2021, 9, 1, 11, 24, 57, 290428, tzinfo=utc)),
        ),
    ]
