# Generated by Django 3.1 on 2020-09-09 10:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('premium', '0013_auto_20200901_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkmembershipactivity',
            name='expiry',
            field=models.DateField(default=datetime.datetime(2021, 9, 9, 10, 30, 59, 338278, tzinfo=utc)),
        ),
    ]
