# Generated by Django 3.1 on 2020-09-24 14:01

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('premium', '0014_auto_20200909_1601'),
    ]

    operations = [
        migrations.RenameField(
            model_name='networkmembershipactivity',
            old_name='active_till',
            new_name='trial_active_till',
        ),
        migrations.RemoveField(
            model_name='networkmembershipactivity',
            name='expiry',
        ),
        migrations.RemoveField(
            model_name='networkmembershipactivity',
            name='payment',
        ),
        migrations.AddField(
            model_name='networkmembershipactivity',
            name='trial_applied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='networkmembershipactivity',
            name='trial_expiry',
            field=models.DateField(default=datetime.datetime(2021, 9, 24, 14, 1, 11, 227410, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='NetworkMembershipSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('payment', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('started', models.DateField(default=django.utils.timezone.now)),
                ('is_trial', models.BooleanField(default=False)),
                ('expiry', models.DateField(default=datetime.datetime(2021, 9, 24, 14, 1, 11, 227410, tzinfo=utc))),
                ('active_till', models.IntegerField(blank=True, default=365, null=True)),
                ('active', models.BooleanField(default=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='premium.networkmembershipactivity')),
            ],
        ),
    ]
