# Generated by Django 3.1 on 2020-09-24 14:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('premium', '0015_auto_20200924_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkmembershipactivity',
            name='trial_expiry',
            field=models.DateField(default=datetime.datetime(2021, 9, 24, 14, 48, 36, 130654, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='networkmembershipsubscription',
            name='expiry',
            field=models.DateField(default=datetime.datetime(2021, 9, 24, 14, 48, 36, 130654, tzinfo=utc)),
        ),
    ]
