# Generated by Django 3.1 on 2020-10-01 10:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('premium', '0018_auto_20200930_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkmembershipactivity',
            name='trial_expiry',
            field=models.DateField(default=datetime.datetime(2021, 10, 1, 10, 11, 23, 140480, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='networkmembershipsubscription',
            name='expiry',
            field=models.DateField(default=datetime.datetime(2021, 10, 1, 10, 11, 23, 140480, tzinfo=utc)),
        ),
    ]
