# Generated by Django 3.1 on 2021-01-14 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('premium', '0021_auto_20201224_1939'),
        ('premium', '0022_auto_20201222_1921'),
    ]

    operations = [
    ]
