# Generated by Django 3.1 on 2021-03-09 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
        ('orders', '0004_auto_20210204_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='billing_address',
            field=models.ForeignKey(blank=True, help_text='Reference to the Address added by the user. This will be used as billing address for the user', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='billing_address', to='addresses.address'),
        ),
    ]
