# Generated by Django 3.1 on 2021-03-13 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20210309_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_pickup',
            field=models.BooleanField(blank=True, default=False, help_text="If this is true then the order have been opted for pickup. Don't need to take the address from the user and can be passed null.", null=True),
        ),
    ]
